<a href="https://colab.research.google.com/github/Naseungchae/Study-Records/blob/main/Activation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activation Layers

In [21]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# input
x = tf.random.normal(shape=(1, 5))

# activation function in TF
a_sigmoid = sigmoid(x)
a_tanh = tanh(x)
a_relu = relu(x)

# activation function self
a_sigmoid_self = 1/(1+exp(-x))
a_tanh_self = (exp(x)-exp(-x))/(exp(x)+exp(-x))
a_relu_self = maximum(x, 0)

# 결과확인
print('-'*100)
print(f'input : {x}\ninput shape : {x.shape}')
print('-'*100)
print(f'sigmoid : {a_sigmoid}\nshape : {a_sigmoid.shape}')
print(f'sigmoid self : {a_sigmoid_self}\nshape : {a_sigmoid_self.shape}')
print('-'*100)
print(f'tanh : {a_tanh}\nshape : {a_tanh.shape}')
print(f'tanh self : {a_tanh_self}\nshape : {a_tanh_self.shape}')
print('-'*100)
print(f'ReLU : {a_relu}\nshape : {a_relu.shape}')
print(f'ReLU self : {a_relu_self}\nshape : {a_relu_self.shape}')
print('-'*100)

----------------------------------------------------------------------------------------------------
input : [[-1.1684254 -1.0924305 -0.1009689  1.296544  -0.7701441]]
input shape : (1, 5)
----------------------------------------------------------------------------------------------------
sigmoid : [[0.23713973 0.25116092 0.4747792  0.7852528  0.31644794]]
shape : (1, 5)
sigmoid self : [[0.23713969 0.2511609  0.47477922 0.78525275 0.3164479 ]]
shape : (1, 5)
----------------------------------------------------------------------------------------------------
tanh : [[-0.8237668  -0.79776347 -0.10062718  0.8608308  -0.64701325]]
shape : (1, 5)
tanh self : [[-0.8237667  -0.7977635  -0.10062722  0.8608307  -0.6470132 ]]
shape : (1, 5)
----------------------------------------------------------------------------------------------------
ReLU : [[0.       0.       0.       1.296544 0.      ]]
shape : (1, 5)
ReLU self : [[0.       0.       0.       1.296544 0.      ]]
shape : (1, 5)
-----------

In [44]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# input
x = tf.random.normal(shape=(1, 5))

# affine to activation(= artificial neurons)
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# in TF
z_sigmoid = dense_sigmoid(x)
z_tanh = dense_tanh(x)
z_relu = dense_relu(x)

# self
W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1/(1+exp(-z))


print('-'*50)
print(f'sigmoid : {z_sigmoid}\nshape : {z_sigmoid.shape}')
print(f'sigomid self : {a}\nshape : {a.shape}')
print('-'*50)
print(f'tanh : {z_tanh}\nshape : {z_tanh.shape}')
print('-'*50)
print(f'relu : {z_relu}\nshape : {z_relu.shape}')
print('-'*50)

--------------------------------------------------
sigmoid : [[0.72893363]]
shape : (1, 1)
sigomid self : [[0.7289337]]
shape : (1, 1)
--------------------------------------------------
tanh : [[-0.17096911]]
shape : (1, 1)
--------------------------------------------------
relu : [[0.62950206]]
shape : (1, 1)
--------------------------------------------------


# Artificial Neurons

In [55]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# actiations
#activation = 'sigmoid'
activation = 'tanh'
#activation = 'relu'

# input
x = tf.random.uniform(shape=(1, 10))

dense = Dense(units=1, activation=activation)

# activation values (tf)
a_tf = dense(x)

W, B = dense.get_weights()

# affine function
z = tf.linalg.matmul(x, W) + B

# activation function (self)
if activation == 'sigmoid':
  a_self = 1 / (1+exp(-z))
elif activation == 'tanh':
  a_self = (exp(z) - exp(-z)) / (exp(z) + exp(-z))
elif activation == 'relu':
  a_self = maximum(z, 0)

# tf와 self의 결과 비교
print('activation :', activation)
print('-' * 50)
print(f'tensorflow values : {a_tf}\ntensorflow shape : {a_tf.shape}')
print('-' * 50)
print(f'self values : {a_self}\nself shape : {a_self.shape}')

activation : tanh
--------------------------------------------------
tensorflow values : [[0.26253963]]
tensorflow shape : (1, 1)
--------------------------------------------------
self values : [[0.26253965]]
self shape : (1, 1)


# Minibatches

In [73]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

rows, columns = (10, 5)
x = tf.random.normal(shape=(rows, columns))

dense = Dense(units=1, activation='relu')

a = dense(x)

W, B = dense.get_weights()
# weight vector와 x vector의 원소의 수가 같다.
# input의 값이 매우 크더라도 weight와 bias에는 영향을 미치지 않는다.

print(f'input : {x}\ninput shape : {x.shape}')
print('-'*100)
print(f'AN result : {a}\nAN result shape : {a.shape}')
print('-'*100)
print(f'weight : {W}\nweight shape : {W.shape}')
print('-'*100)
print(f'bias : {B}\nbias shape : {B.shape}')

input : [[-0.13798486 -0.8627733   0.7121647  -1.0419962  -1.2714546 ]
 [-1.4203466   1.5138279  -0.18936908 -1.9050298   0.24263842]
 [ 0.29847926  1.1178148  -0.23357949  1.6604189   0.2085779 ]
 [-1.2465956  -1.7881794   0.19560383 -1.4737003   0.80441195]
 [ 0.16830213  0.63466066 -1.1224179   1.6603878  -0.3011508 ]
 [ 0.01422106  0.2750876  -0.39066204  1.2619158  -0.6976057 ]
 [-1.6843828   1.752625    2.2481673  -0.59669095 -2.4951553 ]
 [ 0.46834317 -0.11470162  0.38362548  1.2190887   0.27743915]
 [-0.12113705  0.146509    1.6190236  -0.0957462   2.3193278 ]
 [ 0.7542803   1.1805868  -0.26500744  0.15817168  0.537815  ]]
input shape : (10, 5)
----------------------------------------------------------------------------------------------------
AN result : [[0.       ]
 [1.1159724]
 [0.       ]
 [2.508444 ]
 [0.       ]
 [0.       ]
 [0.       ]
 [0.       ]
 [2.5538898]
 [0.       ]]
AN result shape : (10, 1)
---------------------------------------------------------------------

In [80]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activations
#activation = 'sigmoid'
activation = 'tanh'
#activation = 'relu'

# tensorflow
rows, columns = (8, 5)
x = tf.random.normal(shape=(rows, columns))
dense = Dense(units=1, activation=activation)
a = dense(x)
W, B = dense.get_weights()

# self
z = tf.linalg.matmul(x, W) + B

if activation == 'sigmoid':
  aa = 1 / (1+exp(-z))
elif activation == 'tanh':
  aa = (exp(z) - exp(-z)) / (exp(z) + exp(-z))
elif activation == 'relu':
  aa = maximum(z, 0)

# 결과확인
print(f'input data : {x}\ninput data shape{x.shape}')
print('-' * 50)
print('activation :', activation)
print('-' * 50)
print(f'tensorflow values : {a}\ntensorflow shape : {a.shape}')
print('-' * 50)
print(f'self values : {aa}\nself shape : {aa.shape}')

input data : [[-0.30836308  0.39828965  0.3355299  -0.8995933   1.9336692 ]
 [-2.2704241  -0.16890718  0.8711445  -0.9117264   1.61569   ]
 [ 0.0048891   0.42538434 -1.0626311   1.2942739   0.4300091 ]
 [-0.18490323  0.29024556 -0.7636409  -0.23308073 -0.3172304 ]
 [ 1.640871    0.10306201 -0.4999066   0.48209673 -0.17698506]
 [ 0.33717853 -0.67567885 -1.135925   -0.55840194 -0.4015542 ]
 [ 0.3060402   1.3459566   0.03700842  0.73016626 -0.51937664]
 [ 0.59074306 -0.75387174 -0.54591477 -0.27347305  0.05438825]]
input data shape(8, 5)
--------------------------------------------------
activation : tanh
--------------------------------------------------
tensorflow values : [[ 0.87749785]
 [-0.2797238 ]
 [ 0.90921277]
 [ 0.25181752]
 [ 0.7441951 ]
 [ 0.21056496]
 [ 0.27786103]
 [ 0.31054795]]
tensorflow shape : (8, 1)
--------------------------------------------------
self values : [[ 0.87749785]
 [-0.27972376]
 [ 0.9092127 ]
 [ 0.25181755]
 [ 0.74419504]
 [ 0.21056502]
 [ 0.27786106]
 [