<a href="https://colab.research.google.com/github/Naseungchae/Study-Records/blob/main/Dense_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dense layer

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# input
N , n_feature = 1, 10 # 1행 10열
x = tf.random.normal(shape=(N, n_feature))

# Dense layer
n_nueron = 3
dense = Dense(units=n_nueron, activation='sigmoid') # 3개의 뉴런과 activation function으로 sigmoid를 갖는 dense layer
# 해당 Dense layer에서 만들어지는 weight matrix의 shape은 10행 3열
# 해당 Dense layer에서 만들어지는 bias vector의 shape은 row vector

# output(activation value)
a = dense(x) # 1행 3열
W, B = dense.get_weights()

# 결과확인
print('-'*100)
print(f'input : {x}\ninput shape : {x.shape}')
print('-'*100)
print(f'output : {a}\noutput shape : {a.shape}')
print('-'*100)
print(f'weight : {W}\nWeight shape : {W.shape}')
print('-'*100)
print(f'bias : {B}\nbias shape : {B.shape}')
print('-'*100)

----------------------------------------------------------------------------------------------------
input : [[ 0.22468439 -0.02518503  0.40026894 -0.5262036   1.7936236  -1.0527855
  -1.9100151  -0.35860032  0.47279286 -0.26644725]]
input shape : (1, 10)
----------------------------------------------------------------------------------------------------
output : [[0.57310957 0.3625689  0.46520996]]
output shape : (1, 3)
----------------------------------------------------------------------------------------------------
weight : [[ 0.548908   -0.29520276 -0.16253799]
 [ 0.4742838   0.45995498 -0.6745634 ]
 [-0.3401522   0.13121623 -0.20248717]
 [-0.20929587  0.00887841 -0.17741466]
 [ 0.44852638 -0.30910316 -0.12785524]
 [ 0.22438955 -0.25018886  0.20672423]
 [ 0.0923934   0.11958325 -0.33657208]
 [ 0.39221513 -0.22034183  0.22521693]
 [ 0.26597285 -0.4190487  -0.5683901 ]
 [ 0.629388   -0.39168665 -0.08044672]]
Weight shape : (10, 3)
---------------------------------------------------

In [33]:
import numpy as np
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

# input
N , n_feature = 5, 10
x = tf.random.normal(shape=(N, n_feature))

# Dense layer
n_nueron = 3
dense = Dense(units=n_nueron, activation='sigmoid')

# output(activation value)
a_tf = dense(x)
W, B = dense.get_weights()

# self_1
z = matmul(x, W) + B # affine 
a_self = 1 / (1+exp(-z)) # activation

# self_2 with numpy dot product
output = np.zeros(shape=(N, n_nueron))

for i in range(N):
  x_index = x[i]
  for k in range(n_nueron):
    weight, bias = W[:,k], B[k]
    z = tf.reduce_sum(x_index * weight) + bias
    a = 1 / (1+np.exp(-z))
    output[i, k] = a

print(f'tensorflow output : {a_tf}\ntensorflow output shape : {a_tf.shape}')
print('-'*60)
print(f'self_1 output : {a_self}\nself_1 output shape : {a_self.shape}')
print('-'*60)
print(f'self_2 output : {output}\nself_2 output shape : {output.shape}')

tensorflow output : [[0.8583145  0.04846495 0.54198635]
 [0.36350334 0.07085541 0.23354122]
 [0.57156324 0.7611129  0.28974938]
 [0.34878314 0.4794724  0.85424125]
 [0.3304338  0.5701592  0.82671916]]
tensorflow output shape : (5, 3)
------------------------------------------------------------
self_1 output : [[0.8583145  0.04846497 0.54198635]
 [0.36350334 0.07085543 0.23354122]
 [0.57156324 0.76111287 0.28974938]
 [0.34878314 0.47947243 0.85424125]
 [0.3304338  0.57015926 0.8267191 ]]
self_1 output shape : (5, 3)
------------------------------------------------------------
self_2 output : [[0.85831451 0.04846496 0.54198631]
 [0.36350337 0.07085543 0.23354121]
 [0.57156329 0.76111289 0.28974938]
 [0.34878312 0.47947238 0.85424126]
 [0.33043375 0.57015925 0.82671915]]
self_2 output shape : (5, 3)


# Dense layer 쌓기

In [39]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# input
N, n_feature = 5, 6
x = tf.random.normal(shape=(N, n_feature)) #5행6열

# dense layer
n_nuerons = [5, 3]

dense_1 = Dense(units=n_nuerons[0], activation='sigmoid') # 5개의 뉴런의 수를 갖는 dense layer
dense_2 = Dense(units=n_nuerons[1], activation='sigmoid') # 3개의 뉴런의 수를 갖는 dense layer

# output
a1 = dense_1(x) # 5행5열
a2 = dense_2(a1) # 5행3열

# params
W1, B1 = dense_1.get_weights()
W2, B2 = dense_2.get_weights()

# shape 확인
print(f'input shape : {x.shape}')
print('-'*50)
print(f'a1 shape : {a1.shape}')
print(f'weight shape : {W1.shape}\nbias shape : {B1.shape}')
print('-'*50)
print(f'a2 shape : {a2.shape}')
print(f'weight shape : {W2.shape}\nbias shape : {B2.shape}')

input shape : (5, 6)
--------------------------------------------------
a1 shape : (5, 5)
weight shape : (6, 5)
bias shape : (5,)
--------------------------------------------------
a2 shape : (5, 3)
weight shape : (5, 3)
bias shape : (3,)


## for문으로 Dense layer 효율적으로 쌓기

In [44]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# input
N, n_feature = 5, 6
x = tf.random.normal(shape=(N, n_feature))

# dense layer
n_nuerons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
dense_layers = []

for n in n_nuerons:
  dense = Dense(units=n, activation='relu')
  dense_layers.append(dense)

for index, dense in enumerate(dense_layers):
  x = dense(x) # foward propagation
  print('dense layer index :', index)
  print(f'dense layer shape : {x.shape}')

dense layer index : 0
dense layer shape : (5, 10)
dense layer index : 1
dense layer shape : (5, 20)
dense layer index : 2
dense layer shape : (5, 30)
dense layer index : 3
dense layer shape : (5, 40)
dense layer index : 4
dense layer shape : (5, 50)
dense layer index : 5
dense layer shape : (5, 60)
dense layer index : 6
dense layer shape : (5, 70)
dense layer index : 7
dense layer shape : (5, 80)
dense layer index : 8
dense layer shape : (5, 90)
dense layer index : 9
dense layer shape : (5, 100)


In [51]:
import numpy as np
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_copy = tf.identity(X)

# tensorflow
n_nuerons = [3, 4, 5]
dense_layers = []

for n in n_nuerons:
  dense = Dense(units=n, activation='sigmoid')
  dense_layers.append(dense)

weight, bias = [], []
for index, dense in enumerate(dense_layers):
  X = dense(X)
  W, B = dense.get_weights()

  weight.append(W)
  bias.append(B)

print(X) # output
print('-' * 100)

# self
for index in range(len(n_nuerons)):
  w, b = weight[index], bias[index]
  X_copy = matmul(X_copy, w) + b
  X_copy = 1/(1+exp(-X_copy))

print(X_copy) # output

tf.Tensor(
[[0.56290853 0.7054432  0.41389215 0.37710518 0.480882  ]
 [0.5604748  0.6963535  0.4159508  0.3790667  0.4812168 ]
 [0.5560808  0.69471127 0.41281018 0.38048592 0.4817238 ]
 [0.5519472  0.7069597  0.4016587  0.37331596 0.47684398]], shape=(4, 5), dtype=float32)
----------------------------------------------------------------------------------------------------
tf.Tensor(
[[0.56290853 0.7054432  0.41389212 0.37710515 0.48088202]
 [0.5604749  0.6963535  0.4159508  0.3790667  0.48121682]
 [0.5560808  0.69471127 0.41281018 0.38048592 0.48172373]
 [0.5519472  0.7069598  0.4016587  0.37331596 0.47684392]], shape=(4, 5), dtype=float32)
