# Neural Networks

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

## AND

In [2]:
def AND(a, b):
    inputs = np.array([a, b])
    weights = np.array([0.4, 0.4])
    bias = -0.6
    value = np.sum(inputs * weights) + bias
    
    if value <= 0:
        return 0
    else:
        return 1

In [3]:
print(AND(0, 0))
print(AND(0, 1))
print(AND(1, 0))
print(AND(1, 1))

0
0
0
1


## OR

In [6]:
def OR(a, b):
    inputs = np.array([a, b])
    weights = np.array([0.4, 0.5])
    bias = -0.3
    value = np.sum(inputs * weights) + bias
    
    if value <= 0:
        return 0
    else:
        return 1

In [7]:
print(OR(0, 0))
print(OR(0, 1))
print(OR(1, 0))
print(OR(1, 1))

0
1
1
1


## NAND

In [8]:
def NAND(a, b):
    inputs = np.array([a, b])
    weights = np.array([-0.6, -0.5])
    bias = 0.7
    value = np.sum(inputs * weights) + bias
    
    if value <= 0:
        return 0
    else:
        return 1

In [9]:
print(NAND(0, 0))
print(NAND(0, 1))
print(NAND(1, 0))
print(NAND(1, 1))

1
1
1
0


## XOR

> ***Multi Layer Perceptron***
> - input layer
> - hidden layer
> - output layer

In [10]:
def XOR(x1, x2):
    s1 = NAND(x1,x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [13]:
print(XOR(0, 0))
print(XOR(0, 1))
print(XOR(1, 0))
print(XOR(1, 1))

0
1
1
0


# Activation Function

- 입력 신호의 총 합을 출력 신호로 변환하는 함수이다.
- 활성화 함수에따라 출력값이 결정된다.
- 단층, 다층 퍼셉트론에 모두 사용된다.
- 하나의 층에서 다음 층으로 넘어갈 때에는 항상 활성화함수를 통과한다.

> ***Best Activation Function***  
> - Sigmoid  
> - ReLU  
> - tanh  
> - Identitiy Function  
> - Softmax

## Step Function

In [14]:
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

## Sigmoid

- binary classification에 주로 사용
- 출력값이 0 ~ 1의 값이며, 이는 확률로 표현이 가능하다.

In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

## ReLU

In [16]:
def ReLU(x):
    if x > 0:
        return x
    else:
        return 0

## LeakyReLU

In [22]:
def LeakyReLU(x):
    a = 0.01
    return np.maximum(a*x, x)

## ELU

In [23]:
def ELU(x):
    alpha = 1.0
    return (x >= 0) * x + (x < 0) * alpha * (np.exp(x) - 1)

## tanh

In [18]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

## Identitiy Function

- regression의 문제에서 주로 사용

In [19]:
def identitiy_function(x):
    return x

## Softmax

- multi class clssification에 사용
- 입력값의 영향을 크게 받으며, 입력값이 크면 출력값도 커진다.
- overflow의 문제

In [20]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [21]:
def softmax(a):
    C = np.max(a)
    return (np.exp(a - C) / np.sum(np.exp(a - C)))

# 3 layer Neural Networks

- ***binary classification***

> ***input layer***
>    - 뉴런의 수 3개  

> ***hidden layer***  
>    - 뉴런의 수 3개  
>    - 뉴런의 수 2개  

> ***output layer***  
>    - 뉴런의 수 2개  

In [26]:
X = np.array([1.0, 0.5, 0.4]) 
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6], [0.3, 0.5, 0.7]])
B1 = np.array([1, 1, 1])

print(X.shape)
print(W1.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)

print(A1)
print(Z1)

(3,)
(3, 3)
(3,)
[1.32 1.7  2.08]
[0.78918171 0.84553473 0.88894403]


In [27]:
W2 = np.array([[0.2, 0.4, 0.6], [0.1, 0.3, 0.5], [0.4, 0.6, 0.8]])
B2 = np.array([1, 1, 1])

print(W2.shape)
print(B2.shape)

A2 = np.dot(A1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

(3, 3)
(3,)
[2.266 3.286 4.306]
[0.90602176 0.96394539 0.9866921 ]


In [28]:
W3 = np.array([[0.1, 0.3], [-0.1,-0.5], [0.3, 0.5]])
B3 = np.array([1, 1])

print(W3.shape)
print(B3.shape)

A3 = np.dot(A2, W3) + B3
Z3 = sigmoid(A3)

print(A3)
print(Z3)

(3, 2)
(2,)
[2.1898 2.1898]
[0.8993298 0.8993298]


In [29]:
W4 = np.array([[0.1, 0.2], [0.3, 0.5]])
B4 = np.array([1, 1])

print(W4.shape)
print(B4.shape)

A4 = np.dot(A3, W4) + B4
Y = sigmoid(A4)

print(A4)
print(Y)

(2, 2)
(2,)
[1.87592 2.53286]
[0.86714179 0.92641356]


In [30]:
def networks():
    
    networks = {}
    
    # 첫번째 레이어
    networks["W1"] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6], [0.3, 0.5, 0.7]])
    networks["B1"] = np.array([1, 1, 1])
    
    # 두번째 레이어
    networks["W2"] = np.array([[0.2, 0.4, 0.6], [0.1, 0.3, 0.5], [0.4, 0.6, 0.8]])
    networks["B2"] = np.array([1, 1, 1])
    
    # 세번째 레이어
    networks["W3"] = np.array([[0.1, 0.3], [-0.1,-0.5], [0.3, 0.5]])
    networks["B3"] = np.array([1, 1])

    # 네번째 레이어
    networks["W4"] = W4 = np.array([[0.1, 0.2], [0.3, 0.5]])
    networks["B4"] = np.array([1, 1])
    
    return networks

In [32]:
def forward(networks, x):
    W1, W2, W3, W4 = networks["W1"], networks["W2"], networks["W3"],networks["W4"]
    B1, B2, B3, B4 = networks["B1"], networks["B2"], networks["B3"],networks["B4"]
    
    A1 = np.dot(x, W1) + B1
    Z1 = sigmoid(A1)
    
    A2 = np.dot(Z1, W2) + B2
    Z2 = sigmoid(A1)
                 
    A3 = np.dot(Z2, W3) + B3
    Z3 = sigmoid(A3)
                 
    A4 = np.dot(Z3, W4) + B4
    y = sigmoid(A4)
    
    return y

In [33]:
net = networks()
x = np.array([0.3, 1.3, -2.2])
y = forward(net, x)
print(y)

[0.78685795 0.8228324 ]
