# Numpy

: Numerical Python

* numpy에서 for문을 이용하지 않도록 하기!
* 자세한 기능을 기억할수는 없지만, 이러한 기능도 있다는것을 알아두는것이 유용하게 적용될것!

## import

In [3]:
import numpy as np

## Array creation

* numpy는 **하나의 데이터 타입**만을 배열에 생성할 수 있다.

In [4]:
example = np.array(["1", 3, 5.3, "7", 9], float) 

print(example)

type(example[0]) # == example_1[0].dtype

[1.  3.  5.3 7.  9. ]


numpy.float64

### arrange

: 배열의 범위를 지정하여 설정이 가능하다.

* step을 **소수점** 단위로도 설정이 가능하다. (=list에서는 불가능하기때문에 .tolist()를 사용하는것도 방법)
* 1.4.1의 reshape와 함께 사용하면 메트릭스표현이 가능하다.

In [5]:
np.arange(1, 11, .5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [6]:
np.arange(1, 31).reshape(3, 2, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

### zeros, ones, empty

: 특정한 값 또는 메모리만을 갖는 배열을 생성한다.

In [7]:
np.zeros(shape = 10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### something_like

: 기존의 배열의 모양의 크기만큼 zeros, ones 또는 empty 배열을 반환한다.

In [9]:
example_1 = np.arange(1, 31).reshape(2, 3, 5)

In [10]:
np.zeros_like(example_1)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

### identity (=단위 행렬)

* 디폴트값으로 n * n의 단위행렬을 생성한다.

In [11]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### eye (=대각선이 1인 행렬)

* 디폴트 값으로 k(대각선)는 0번째 위치에 생성되지만, k의 값을 임의로 조정이 가능하다.

In [12]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 전치 행렬

In [13]:
example_4

NameError: name 'example_4' is not defined

In [14]:
example_4.transpose()

NameError: name 'example_4' is not defined

### diag

: 대각 행렬의 값을 추출한다.

In [15]:
example_3 = np.arange(25).reshape(5, 5)

np.diag(example_3)

array([ 0,  6, 12, 18, 24])

### random sampling

: 데이터의 분포에 맞는 샘플링으로 배열을 생성 가능하다.

* uniform은 균등분포
* normal은 정규분포

In [16]:
np.random.uniform(0, 1, 10).reshape(2, 5)

array([[0.97912466, 0.74424735, 0.92021783, 0.66933871, 0.63953463],
       [0.23207366, 0.82487683, 0.04015884, 0.97628743, 0.7312318 ]])

In [17]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-0.74919858, -1.0386688 ,  0.23702281,  1.31476478,  0.09217967],
       [ 1.01033657,  1.92075966, -0.26796407,  0.76337544,  0.42080934]])

## Array Shape
: 생성된 배열의 shape를 확인 할 수 있다.

* vector = (row,)
* matrix = (column, row)
* 3rd order tensor = (depth, column, row)

In [18]:
example.shape

(5,)

### number of demension

: 차원의 수를 반환한다.

In [19]:
example.ndim

1

### size

: 전체 데이터의 수를 반환한다.

In [20]:
example.size

5

## Shape Handling

: 배열의 크기는 같지만, 차원의 수를 변경하는 방법

- 전체 데이터의 수를 고려해서 활용해야 한다.

In [21]:
example_2 = [[1, 2, 3, 4, 5, 6],
            [7, 8, 9, 10, 11, 12]]

np.array(example_2).shape

(2, 6)

### reshape

: 데이터의 수를 고려하여 차원에 반영이 가능하다. (vector -> matrix)

- 특정 row나 column의 수는 알 수 없지만, 하나의 row, column에 대한 수를 알고 있을때에는 **-1**을 활용하면
  데이터의 수에 맞게 reshpe이 된다.

In [22]:
np.array(example_2).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [23]:
np.array(example_2).reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### flatten

: 다차원의 배열을 1차원의 배열로 변환한다.

In [24]:
np.array(example_2).flatten() # == np,array(example_2).reshape(1, -1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Indexing

- list와 유사하지만 더 편리한 접근이 가능하다.
- 새로운 값의 할당도 가능하다.
- 마지막은 n-1임에 유의하기

In [25]:
a = np.array(example_2)

In [26]:
a[0, 2] # == a[0][2] 

3

## Slicing

: [row, column]의 순서로 슬라이싱된다.

* :와 함께 [start, stop, step]의 순서로 접근도 가능하다.
* 마지막은 n-1임에 유의하기

In [27]:
a[:, 2:]

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12]])

In [28]:
a[1, :]

array([ 7,  8,  9, 10, 11, 12])

In [29]:
a[:, ::2]

array([[ 1,  3,  5],
       [ 7,  9, 11]])

## 연산

: 배열의 **모든 요소**들간의 연산을 수행 할 수 있다.

* sum, mean, std, sin, cos, tan, log 외에도 다양한 연산수행이 가능하다.

In [30]:
example_1.sum()

465

### matrix내의 연산

* shape가 같은 경우에 연산을 수행하는 방식.
* matrix.dot(n)은 각각의 matrix에 n만큼의 수를 곱한다(=선형대수)

In [31]:
qp = np.array([[1, 3, 5], [4, 5, 6]])

qp + qp # + - * / // % 모두 가능하다.

array([[ 2,  6, 10],
       [ 8, 10, 12]])

In [32]:
qp.dot(3)

array([[ 3,  9, 15],
       [12, 15, 18]])

### broadcasting

* shape가 다른 경우에 연산을 수행하는 방식

In [33]:
test_matrix = np.arange(1, 25).reshape(4, 6)
test_scalar = 10

test_matrix + test_scalar

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

### axis 연산

: **축**을 지정하여 부분연산을 수행 할 수 있다.

* 새롭게 생성되는 axis가 0이되고 기존의 axis가 존재할 경우 1씩 밀려나게 된다.
* (0, )  ->  (0, 1)  ->  (0, 1, 2)

In [34]:
example_4 = np.arange(1, 13).reshape(3, 4)
example_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
example_4.sum(axis = 1)

array([10, 26, 42])

In [36]:
example_4.sum(axis = 0)

array([15, 18, 21, 24])

## CONCATENATE

- vstack : x축 기준으로 합하는 기능을 수행
- hstack : y축 기준으로 합하는 기능을 수행
- concatenate(axis=)방식으로도 합할 수 있다.
- 추가적인 메모리를 확보해야하기 때문에 연산이 느리다.

In [37]:
q = np.array([1, 3, 5])
p = np.array([2, 4, 6])

np.vstack((q, p))

array([[1, 3, 5],
       [2, 4, 6]])

In [38]:
np.hstack((q, p))

array([1, 3, 5, 2, 4, 6])

##  COMPARE

### all

: 특정 조건을 모두 만족해야 True, 하나라도 만족하지 못한다면 False를 return한다.

In [65]:
exam = np.arange(1, 11)

exam > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [66]:
np.all(exam)

True

### any 

: 하나라도 특정 조건을 만족한다면 True, 모두 만족하지 않는다면 False를 return한다.

In [67]:
np.any(exam)

True

### logical_and

: 2가지의 조건을 모두 만족해야 True를 return한다. (=and)

In [68]:
np.logical_and(exam > 0, exam < 11)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### logical_not

: 특정 조건을 모두 만족하지 않은 경우 False를 return

In [69]:
np.logical_not(exam<0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### logical_or

: 두가지 조건중 하나의 조건이라도 True라면 True (=or)

In [70]:
np.logical_or(exam<0, exam>5)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

### np.whrere

: 조건에 맞는 **index**값을 return

* np.where(condition, True일 경우 return값, False일 경우 return값) : True, False의 경우를 조정할 수 있다.

In [74]:
np.where(exam > 6)

(array([6, 7, 8, 9], dtype=int64),)

In [72]:
np.where(exam>6, 0, 1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

### np.isnan

: NaN(Not a Number)을 찾아 True를 return한다.

* Inf의 경우 False를 return

In [77]:
exam = np.array([1, np.NaN, 3, np.NaN, 5, np.NaN, 7, np.Inf, 9])

exam

array([ 1., nan,  3., nan,  5., nan,  7., inf,  9.])

In [78]:
np.isnan(exam)

array([False,  True, False,  True, False,  True, False, False, False])

### np.isfinite

: finite number을 찾아 return한다.

In [79]:
np.isfinite(exam)

array([ True, False,  True, False,  True, False,  True, False,  True])

### argmax & argmin

: 가장 큰값과 작은값의index를 return한다.

* 축 (=axis)를 지정하면 해당 축에서 조건을 만족하는 값을 return한다

In [80]:
exam = [1, 3, 5 ,77, 99, 0]

np.argmax(exam), np.argmin(exam)

(4, 5)

In [83]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [86]:
np.argmax(a, axis = 1)

array([5, 5], dtype=int64)

## boolean index 

: 배열에서 특정 조건에 맞는 값을 배열 형태로 추출할 수 있다.

* 조건이 True인 index의 element만을 추출한다.
* where절과 같이 활용하면 유용하게 사용 가능할 듯

In [100]:
exam = np.arange(1, 51)

exam % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [102]:
exam[exam%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

## fancy index

: 배열을 index value로 시용해서 값을 추출하는 방법이다.
* matrix의 형태로도 활용이 가능하다.

In [104]:
a = np.arange(1, 11)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
b = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], int) # 반드시 integer로 선언해야 한다.

In [107]:
a[b] # == a.take[b]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [112]:
c = np.array([9, 8, 7, 6, 5, 4, 0, 0, 0, 0], int) # 인덱스를 중복으로 주어 같은 값을 설정할 수 있다.

In [111]:
a[c] # == a.take[c]

array([10,  9,  8,  7,  6,  5,  1,  1,  1,  1])