# 텐서플로우 시작하기

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.8.0


# 텐서의 객체
- **타입(type)** : string, float32, float16, int32, int8 등등  
- **형상(shape)** : 0, 1, 2차원 등의 데이터 차원
- **축(rank)** : 차원의 개수

## 텐서의 차원과 연산

In [3]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

# 상수 역할의 텐서 선언
# 0차원
# a = 2

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [4]:
b = tf.constant([2, 3])
print(tf.rank(b))
print(b)

# 1차원
# b = [2, 3]

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [8]:
c = tf.constant([[2, 3], [6, 7]]) 
print(tf.rank(c))
print(c)

# 2차원
# c = [[2, 3], [6, 7]]

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [10]:
d = tf.constant(["tensorflow"])
print(tf.rank(d))
print(d)

# 1차원
# d = "tensorflow"

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'tensorflow'], shape=(1,), dtype=string)


# 난수생성

In [15]:
random_uniform = tf.random.uniform([1], 0, 1)
print(random_uniform.shape)
print(random_uniform)

# random은 shape [1], 0 ~ 1사이인 값(균등분포)

(1,)
tf.Tensor([0.6491188], shape=(1,), dtype=float32)


In [25]:
random_normal = tf.random.normal([1, 2], 0, 1)
print(random_normal.shape)
print(random_normal)

# random은 shape [1, 2], 평균 0, 표준편차 1인 값(정규분포)

(1, 2)
tf.Tensor([[-0.979869   0.8118605]], shape=(1, 2), dtype=float32)


# 즉시 실행 모드(Eager Mode) 지원

- 즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있다.
- 1.x 버전에서는 "그래프"를 생성하고, 초기화 한 뒤에 세션을 통해 **값을 흐르게 하는 작업**을 진행해야 한다.

In [29]:
a = tf.constant(3)
b = tf.constant(2)

print("+")
print(tf.add(a, b))
print(a + b)
print()
print("-")
print(tf.subtract(a, b))
print(a - b)
print()
print("*")
print(tf.multiply(a, b))
print(a * b)

+
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)

-
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)

*
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


# 텐서플로우 ↔ 넘파이

- **numpy()**
- **tf.convet_to_tensor()**

In [31]:
c = tf.add(a, b).numpy()
print(type(c))

<class 'numpy.int32'>


In [32]:
c_sqaure = np.square(c, dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_sqaure)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


# 넘파이처럼 사용하기

In [35]:
t = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [36]:
print(t[:, 1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [37]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [38]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [39]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [40]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

# 타입 변환
- **텐서의 기본 dtype**
> - float형 텐서 : float32
> - int형 텐서 : int32

- **연산시 텐서의 타입을 맞춰줘야 함**
> - float32 ~ float32 : O
> - int32 ~ int32 : O
> - float32 ~ int32 : X

- **타입 변환에는 tf.cast() 사용**

In [7]:
# tf.constant(2.0) + tf.constant(40)

# 타입이 다르기 때문에 에러가 발생

In [9]:
# tf.constant(2.0) + tf.constant(3.0, dtype=tf.float64)

# 데이터타입이 같은 float형 이지만, 비트가 달라도 에러가 발생

In [10]:
a = tf.constant(30.0, dtype=tf.float64)
b = tf.constant(4.0)

print(tf.cast(a, tf.float32) + b)

# a의 타입을 맞추어 실행이 가능

tf.Tensor(34.0, shape=(), dtype=float32)


# 오토그래프

- **tf.Graph**
- tensorflow가 작업을 좀 더 빠르게 동작하게 하기 위한 방법으로 graph로 만들어 연산을 진행
- 유연성

In [11]:
import timeit

## @tf.function

- 자동으로 그래프를 생성
- 그래프로 변환하여 사용하기때문에 GPU연산이 가능
- 파이썬으로 구성된 함수를 텐서플로우의 그래프로 다루고 싶을 떄 사용가능
- 원본 함수가 필요하다면 (tf.function).python_function()

In [12]:
@tf.function
def test_f(x):
    return x**2 - 10*x + 3

print(test_f(2))
print(test_f(tf.constant(2)))

# 모두 텐서 형태의 결과가 나옴

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [14]:
def test_f_n(x):
    return x**2 - 10*x + 3

print(test_f_n(2))
print(test_f_n(tf.constant(2)))

# 다른 결과가 나옴

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [15]:
test_change = tf.function(test_f_n)

print(test_change)
print(test_change(2))

# 해당 방식으로 변환하는 것도 가능하다.

tf.Tensor(-13, shape=(), dtype=int32)


In [16]:
test_change.python_function(2)

# 변환하기 전의 함수의 기능이 필요하다면
# 해당 방식으로 활용이 가능하다.

-13

In [19]:
def get_faster(x, y, b):
    x = tf.matmul(x, y)
    x = x+b
    return x

use_graph = tf.function(get_faster)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

use_graph(x1, y1, b1).numpy()

array([[12.]], dtype=float32)

In [21]:
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x+b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)

outer_function(tf.constant([[1.0, 2.0]])).numpy()

array([[12.]], dtype=float32)

텐서플로우가 **tf.function**으로 변환한 코드

In [23]:
print(tf.autograph.to_code(test_change.python_function))
print()
print(tf.autograph.to_code(outer_function.python_function))

def tf__test_f_n(x):
    with ag__.FunctionScope('test_f_n', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.ld(x) ** 2 - 10 * ag__.ld(x) + 3
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)


def tf__outer_function(x):
    with ag__.FunctionScope('outer_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        y = ag__.converted_call(ag__.ld(tf).constant, ([[2.0], [3.0]],), None, fscope)
        b = ag__.converted_call(ag__.ld(tf).constant, (4.0,), None, fscope)
        try:
            do_return = True
            retval_ = ag__.co

**속도 향상**

In [27]:
class SequentialModel(tf.keras.Model):
    def __init__(self, **kwargs):
        super(SequentialModel, self).__init__(**kwargs)
        self.flatten = tf.keras.layers.Flatten(input_shape=(28, 28))
        self.dense_1 = tf.keras.layers.Dense(128, activation="relu")
        self.dropout = tf.keras.layers.Dropout(0.2)
        self.dense_2 = tf.keras.layers.Dense(10)
        
    def call(self, x):
        x = self.flatten(x)
        x = self.dense_1(x)
        x = self.dropout(x)
        x = self.dense_2(x)
        return x
    
input_data = tf.random.uniform([60, 28, 28])

eager_model = SequentialModel()
graph_model = tf.function(eager_model)

print("Eager model time : ", timeit.timeit(lambda: eager_model(input_data), number=10000))
print("Graph model time : ", timeit.timeit(lambda: graph_model(input_data), number=10000))

# eager 모드로는 동작을 확인하고
# 실제의 동작은 graph로 동작하는게 좋다

Eager model time :  13.160503999999946
Graph model time :  5.34745410000005
