# 텐서플로우 시작하기

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.3.0


# 텐서의 객체
- **타입(type)** : string, float32, float16, int32, int8 등등  
- **형상(shape)** : 0, 1, 2차원 등의 데이터 차원
- **축(rank)** : 차원의 개수

## 텐서의 차원과 연산

In [3]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

# 상수 역할의 텐서 선언
# 0차원
# a = 2

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [4]:
b = tf.constant([2, 3])
print(tf.rank(b))
print(b)

# 1차원
# b = [2, 3]

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [8]:
c = tf.constant([[2, 3], [6, 7]]) 
print(tf.rank(c))
print(c)

# 2차원
# c = [[2, 3], [6, 7]]

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [10]:
d = tf.constant(["tensorflow"])
print(tf.rank(d))
print(d)

# 1차원
# d = "tensorflow"

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'tensorflow'], shape=(1,), dtype=string)


# 난수생성

In [15]:
random_uniform = tf.random.uniform([1], 0, 1)
print(random_uniform.shape)
print(random_uniform)

# random은 shape [1], 0 ~ 1사이인 값(균등분포)

(1,)
tf.Tensor([0.6491188], shape=(1,), dtype=float32)


In [25]:
random_normal = tf.random.normal([1, 2], 0, 1)
print(random_normal.shape)
print(random_normal)

# random은 shape [1, 2], 평균 0, 표준편차 1인 값(정규분포)

(1, 2)
tf.Tensor([[-0.979869   0.8118605]], shape=(1, 2), dtype=float32)


# 즉시 실행 모드(Eager Mode) 지원

- 즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있다.
- 1.x 버전에서는 "그래프"를 생성하고, 초기화 한 뒤에 세션을 통해 **값을 흐르게 하는 작업**을 진행해야 한다.

In [29]:
a = tf.constant(3)
b = tf.constant(2)

print("+")
print(tf.add(a, b))
print(a + b)
print()
print("-")
print(tf.subtract(a, b))
print(a - b)
print()
print("*")
print(tf.multiply(a, b))
print(a * b)

+
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)

-
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)

*
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


# 텐서플로우 ↔ 넘파이

- **numpy()**
- **tf.convet_to_tensor()**

In [31]:
c = tf.add(a, b).numpy()
print(type(c))

<class 'numpy.int32'>


In [32]:
c_sqaure = np.square(c, dtype = np.float32)
c_tensor = tf.convert_to_tensor(c_sqaure)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


# 넘파이처럼 사용하기

In [35]:
t = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [36]:
print(t[:, 1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [37]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [38]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [39]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [40]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

# 타입 변환
- **텐서의 기본 dtype**
> - float형 텐서 : float32
> - int형 텐서 : int32

- **연산시 텐서의 타입을 맞춰줘야 함**
> - float32 ~ float32 : O
> - int32 ~ int32 : O
> - float32 ~ int32 : X

- **타입 변환에는 tf.cast() 사용**